function net = train_net(X, Y, layers, softmax)
  % Solve a Pattern Recognition Problem with a Neural Network
  % Script generated by NPRTOOL
  % Created Fri Mar 29 15:47:16 EDT 2013
  %
  % This script assumes these variables are defined:
  %
  %   X - input data.
  %   Y - target data.

  if nargin < 4
     softmax = 0;
  end

  % Get input and output.
  inputs = X';
  targets = Y';

  % Create a Pattern Recognition Network
  net = patternnet(layers);

  % Setup Division of Data for Training, Validation, Testing
  net.divideParam.trainRatio = 80/100;
  net.divideParam.valRatio = 10/100;
  net.divideParam.testRatio = 10/100;

  % Set output to softmax.
  if softmax
    net.layers{size(layers, 2) + 2}.transferFcn = 'softmax';
  end

  % Train the Network
  [net,tr] = train(net, inputs, targets);
end
